function dashboardView() {
  return `
  <div class="dashboard-grid">
    <article class="dash-card subscription-card">
      <div class="subscription-state">Подписка активна <i>✓</i></div>
      <span class="days-label">Осталось</span><div class="days-value">184 <small>дня</small></div><span class="metric-caption">до 25 января 2027</span>
      <img src="./assets/mascot/success.svg" alt="Радостная Анфиса" />
      <div class="subscription-meta"><div><span>Тариф</span><strong>6 месяцев</strong></div><div><span>Устройства</span><strong>3 из 4</strong></div></div>
      <button class="button button-primary full" data-action="pay-half-year">Продлить</button>
    </article>
    <article class="dash-card"><div class="dash-card-label">Трафик <span>⌁</span></div><div class="metric-big">128,4 ГБ</div><div class="metric-caption">За текущий период<br />Без ограничений</div><div class="mini-chart"><svg viewBox="0 0 200 70" preserveAspectRatio="none"><path d="M0 60 C20 53,25 30,45 40 S75 55,93 28 S120 55,140 25 S170 38,200 12" fill="none" stroke="currentColor" stroke-width="3" style="color:var(--green)"/><path d="M0 60 C20 53,25 30,45 40 S75 55,93 28 S120 55,140 25 S170 38,200 12 L200 70 L0 70Z" fill="color-mix(in srgb,var(--green) 12%,transparent)"/></svg></div></article>
    <article class="dash-card"><div class="dash-card-label">Устройства <span>▣</span></div><div class="metric-big">3 / 4</div><div class="metric-caption">Можно подключить ещё одно устройство</div><button class="button button-ghost full" style="margin-top:25px" data-route-go="devices">Управление</button></article>
    <article class="dash-card"><div class="dash-card-label">Страны <span>🌱</span></div><div class="metric-caption" style="margin-top:15px">Доступно более 50 вариантов</div><div class="country-mini"><span>🇳🇱</span><span>🇩🇪</span><span>🇺🇸</span><span>🇯🇵</span><span>🇫🇮</span></div></article>
    <article class="dash-card quick-actions-card"><button class="quick-action" data-route-go="connect"><span>⌁</span>Подключить устройство</button><button class="quick-action" data-action="show-qr"><span>▦</span>Показать QR-код</button><button class="quick-action" data-action="pay-half-year"><span>♕</span>Продлить подписку</button><button class="quick-action" data-route-go="devices"><span>▣</span>Устройства</button></article>
  </div>
  <div class="dashboard-lower">
    <article class="dash-card"><div class="dash-card-label">Последние платежи <button class="text-button" data-route-go="payments">Все →</button></div><ul class="list-clean"><li class="list-row"><div><strong>1 500 ₽</strong><span>6 месяцев · 11 июля 2026</span></div><em class="success-pill">Успешно</em></li><li class="list-row"><div><strong>100 ₽</strong><span>Доп. устройство · 11 июля 2026</span></div><em class="success-pill">Успешно</em></li><li class="list-row"><div><strong>800 ₽</strong><span>3 месяца · 11 апреля 2026</span></div><em class="success-pill">Успешно</em></li></ul></article>
    <article class="dash-card"><div class="dash-card-label">Автопродление</div><div class="toggle-row"><div><strong>${state.autoRenew ? 'Включено' : 'Выключено'}</strong><div class="metric-caption">Оплата с баланса в последний день</div></div><button class="switch" data-action="toggle-renew" aria-label="Переключить автопродление"></button></div><div class="dash-card-label">Баланс</div><div class="metric-big">600 ₽</div><button class="button button-secondary full" data-action="top-up">Пополнить баланс</button></article>
    <article class="dash-card support-dash"><div class="dash-card-label">Поддержка</div><p>Не знаете, с чего начать? Анфиса подскажет по-человечески.</p><button class="button button-primary" data-route-go="support">Открыть поддержку</button><img src="./assets/mascot/support.svg" alt="Анфиса в поддержке" /></article>
  </div>`;
}

function connectView() {
  const p = platforms[state.platform];
  return `<div class="page-grid"><section class="panel"><h2>Выберите устройство</h2><p class="panel-subtitle">Покажем только нужные для него действия.</p><div class="platform-tabs">${Object.entries(platforms).map(([key, item]) => `<button class="platform-tab ${key === state.platform ? 'active' : ''}" data-select-platform="${key}"><span>${item.icon}</span>${item.label}</button>`).join('')}</div><div class="recommended-app"><div class="app-icon">${p.app}</div><div><h3>${p.app} <span class="success-pill">Рекомендуем</span></h3><p>Простое и стабильное приложение для ${p.label}</p></div><button class="button button-primary" data-action="install-app">${p.store}</button><img src="./assets/mascot/phone.svg" alt="" /></div><div class="install-steps"><div class="install-step"><b>1</b><div><strong>Установите ${p.app}</strong><span>Нажмите кнопку выше и дождитесь установки.</span></div></div><div class="install-step"><b>2</b><div><strong>Добавьте подключение</strong><span>Откройте QR-код или нажмите кнопку автоматического добавления.</span></div></div><div class="install-step"><b>3</b><div><strong>Нажмите большую кнопку в приложении</strong><span>Анфиса проверит, что всё получилось.</span></div></div></div><details class="accordion-row"><summary>Другие приложения и ручная настройка</summary><div class="alternate-apps">${p.alternatives.map((x) => `<div class="alternate-app"><span>${x}</span><button class="small-button">Инструкция</button></div>`).join('')}</div></details></section><aside class="panel qr-panel"><h3>Добавить по QR-коду</h3><p class="panel-subtitle">Откройте приложение и отсканируйте код.</p><div class="qr-fake"></div><button class="button button-secondary full" data-action="copy-link">Скопировать ключ подключения</button><img src="./assets/mascot/qr.svg" alt="Анфиса показывает QR-код" /></aside></div>`;
}

function devicesView() {
  return `<div class="page-grid"><section class="panel"><h2>Подключённые устройства</h2><p class="panel-subtitle">Отключайте только те устройства, которыми больше не пользуетесь.</p><div class="device-list">${state.devices.map((d) => `<div class="device-item"><div class="device-icon">${d.icon}</div><div><strong>${escapeHtml(d.name)}</strong><span>${d.type} · ${d.lastSeen}</span></div><div class="device-actions"><button class="small-button" data-rename-device="${d.id}">Переименовать</button><button class="small-button danger" data-remove-device="${d.id}">Отключить</button></div></div>`).join('')}</div></section><aside class="panel"><img src="./assets/mascot/laptop.svg" alt="Анфиса с ноутбуком" style="height:180px;display:block;margin:auto"/><h3>3 из 4 мест занято</h3><p class="panel-subtitle">В подписку входят три устройства. Ещё одно добавлено отдельно.</p><button class="button button-primary full" style="margin-top:18px" data-action="add-device">Добавить ещё за 100 ₽</button></aside></div>`;
}

function plansView() {
  return `<div class="plan-grid" style="margin-top:12px"><article class="plan-card"><span class="plan-period">1 месяц</span><div class="plan-price">300 <small>₽</small></div><span class="plan-note">300 ₽ в месяц</span><ul><li>3 устройства</li><li>Без ограничений</li><li>Дни суммируются</li></ul><button class="button button-secondary full" data-plan="month">Продлить</button></article><article class="plan-card featured"><span class="plan-badge">Выгоднее на 11%</span><span class="plan-period">3 месяца</span><div class="plan-price">800 <small>₽</small></div><span class="plan-note">267 ₽ в месяц</span><ul><li>3 устройства</li><li>Без ограничений</li><li>Дни суммируются</li></ul><button class="button button-primary full" data-plan="quarter">Продлить</button></article><article class="plan-card"><span class="plan-badge secondary">Выгоднее на 17%</span><span class="plan-period">6 месяцев</span><div class="plan-price">1 500 <small>₽</small></div><span class="plan-note">250 ₽ в месяц</span><ul><li>3 устройства</li><li>Без ограничений</li><li>Дни суммируются</li></ul><button class="button button-secondary full" data-plan="half-year">Продлить</button></article></div><div class="extra-device-banner"><img src="./assets/mascot/banana.svg" alt="Анфиса с бананом"/><div><strong>Дополнительное устройство</strong><span>100 ₽ в месяц за каждое место сверх трёх.</span></div><button class="button button-ghost" data-action="add-device">Добавить</button></div>`;
}
