function paymentsView() {
  return `<div class="page-grid"><section class="panel"><h2>История платежей</h2><table class="payment-table"><thead><tr><th>Дата</th><th>Назначение</th><th>Способ</th><th>Сумма</th><th>Статус</th></tr></thead><tbody><tr><td>11.07.2026</td><td>6 месяцев</td><td>СБП</td><td>1 500 ₽</td><td><span class="success-pill">Успешно</span></td></tr><tr><td>11.07.2026</td><td>Доп. устройство</td><td>Баланс</td><td>100 ₽</td><td><span class="success-pill">Успешно</span></td></tr><tr><td>11.04.2026</td><td>3 месяца</td><td>СБП</td><td>800 ₽</td><td><span class="success-pill">Успешно</span></td></tr><tr><td>11.03.2026</td><td>1 месяц</td><td>СБП</td><td>300 ₽</td><td><span class="success-pill">Успешно</span></td></tr></tbody></table></section><aside class="panel balance-card"><h3>Баланс</h3><div class="balance-amount">600 ₽</div><p class="panel-subtitle">Средства будут использованы для автопродления.</p><button class="button button-primary full" style="margin-top:18px" data-action="top-up">Пополнить через СБП</button><div class="toggle-row"><div><strong>Автопродление</strong><span class="panel-subtitle">${state.autoRenew ? 'Включено' : 'Выключено'}</span></div><button class="switch" data-action="toggle-renew"></button></div></aside></div>`;
}

function supportView() {
  return `<div class="support-layout"><section class="panel chat-window"><div class="chat-head"><img src="./assets/logo.svg" alt=""/><div><strong>Анфиса</strong><span>онлайн · отвечает сразу</span></div></div><div class="chat-messages" id="chat-messages">${state.chat.map((m) => `<div class="bubble ${m.who}">${escapeHtml(m.text)}</div>`).join('')}</div><form class="chat-compose" id="chat-form"><textarea name="message" placeholder="Напишите, что случилось..." required></textarea><button class="button button-primary" type="submit">➤</button></form></section><aside class="panel"><img src="./assets/mascot/support.svg" alt="Анфиса в наушниках" style="height:185px;display:block;margin:auto"/><h3>Другие способы связи</h3><div class="support-options"><button class="support-option" data-action="open-telegram"><span>✈</span><span><strong>Telegram</strong><small>Перейти в диалог</small></span></button><button class="support-option" data-action="ticket"><span>✉</span><span><strong>Форма обращения</strong><small>Ответ придёт на email</small></span></button><button class="support-option" data-action="faq"><span>?</span><span><strong>Частые вопросы</strong><small>Короткие инструкции</small></span></button></div></aside></div>`;
}

function profileView() {
  return `<div class="profile-grid"><section class="panel"><h2>Основные данные</h2><form class="form-grid" id="profile-form"><div class="field"><label>Имя</label><input name="name" value="Алексей"/></div><div class="field"><label>Email</label><input name="email" type="email" value="alexey@example.com"/></div><div class="field"><label>Логин</label><input name="login" value="alexey"/></div><button class="button button-primary" type="submit">Сохранить</button></form></section><section class="panel"><h2>Способы входа</h2><p class="panel-subtitle">Можно связать несколько способов с одним аккаунтом.</p><div class="social-links"><div class="social-row"><div><span class="social-icon">✈</span><span><strong>Telegram</strong><small class="panel-subtitle">@alexey</small></span></div><span class="success-pill">Подключён</span></div><div class="social-row"><div><span class="social-icon">Я</span><span><strong>Яндекс</strong><small class="panel-subtitle">alexey@yandex.ru</small></span></div><button class="small-button">Подключить</button></div><div class="social-row"><div><span class="social-icon">VK</span><span><strong>VK</strong><small class="panel-subtitle">Не подключён</small></span></div><button class="small-button">Подключить</button></div></div></section></div>`;
}

function adminView() {
  return `<div class="admin-stats"><article class="admin-stat"><span>Пользователи</span><strong>1 248</strong><em class="success-pill">+32 за месяц</em></article><article class="admin-stat"><span>Активные подписки</span><strong>987</strong><em class="success-pill">79%</em></article><article class="admin-stat"><span>Платежи сегодня</span><strong>45 300 ₽</strong><em class="success-pill">+12%</em></article><article class="admin-stat"><span>Сейчас онлайн</span><strong>236</strong><em class="success-pill">Норма</em></article></div><div class="admin-layout"><section class="panel"><div class="dash-card-label">Новые пользователи <select><option>30 дней</option></select></div><div class="bar-chart">${[42,58,49,72,68,91,86,110,103,124,139,151].map((v) => `<div class="bar" style="height:${v}px"><span>${v}</span></div>`).join('')}</div></section><section class="panel"><h3>Состояние интеграций</h3><ul class="list-clean"><li class="list-row"><div><strong>Remnawave API</strong><span>Режим демонстрации</span></div><em class="success-pill">Ожидает ключ</em></li><li class="list-row"><div><strong>СБП</strong><span>Платёжный адаптер</span></div><em class="success-pill">Ожидает ключ</em></li><li class="list-row"><div><strong>Telegram</strong><span>Вход и поддержка</span></div><em class="success-pill">Ожидает ключ</em></li><li class="list-row"><div><strong>AI-помощник</strong><span>Контракт API подготовлен</span></div><em class="success-pill">Черновик</em></li></ul></section></div><section class="panel" style="margin-top:16px"><div class="dash-card-label">Последние пользователи <button class="button button-ghost">Экспорт</button></div><table class="payment-table"><thead><tr><th>Пользователь</th><th>Подписка</th><th>Устройства</th><th>Статус</th><th>Действия</th></tr></thead><tbody><tr><td>alexey@example.com</td><td>до 25.01.2027</td><td>3 / 4</td><td><span class="success-pill">Активна</span></td><td><button class="small-button">Открыть</button></td></tr><tr><td>maria@example.com</td><td>до 11.08.2026</td><td>2 / 3</td><td><span class="success-pill">Активна</span></td><td><button class="small-button">Открыть</button></td></tr><tr><td>ivan@example.com</td><td>закончилась</td><td>1 / 3</td><td><span class="small-button danger">Остановлена</span></td><td><button class="small-button">Открыть</button></td></tr></tbody></table></section>`;
}

function renderCabinet(route) {
  return ({ app: dashboardView, connect: connectView, devices: devicesView, plans: plansView, payments: paymentsView, support: supportView, profile: profileView, admin: adminView }[route] || dashboardView)();
}
